[package]
name = "grow-hardware"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "io-util"] }
nix = { version = "0.29.0", features = ["ioctl"] }
