[package]
name = "grow-agent"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rppal.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
chrono.workspace = true
env_logger.workspace = true
log.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
    "time",
    "sync",
    "signal",
    "fs",
    "rt",
    "io-util",
] }
tokio-util = { workspace = true, features = ["rt"] }
grow-utils.workspace = true
grow-measure.workspace = true
