[package]
name = "grow-agent"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4.4.4", features = ["derive", "env"] }
env_logger = "0.10.0"
log = "0.4.20"
rppal = "0.14.1"
thiserror = "1.0.48"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread", "time"] }
