[package]
name = "grow-agent"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rppal = "0.14.1"
nix = { version = "0.27.1", features = ["ioctl"] }
chrono.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
env_logger.workspace = true
log.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
    "time",
    "sync",
    "signal",
    "fs",
    "rt",
    "io-util",
] }
tokio-util = { workspace = true, features = ["rt"] }
common.workspace = true
api.workspace = true
