[package]
name = "grow-agent"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
chrono = "0.4.31"
clap = { version = "4.4.4", features = ["derive", "env"] }
env_logger = "0.10.0"
log = "0.4.20"
nix = { version = "0.27.1", features = ["ioctl"] }
rppal = "0.14.1"
thiserror = "1.0.48"
tokio = { version = "1.32.0", features = [
    "macros",
    "rt-multi-thread",
    "time",
    "sync",
    "signal",
    "fs",
    "rt",
    "io-util",
] }
tokio-util = "0.7.9"
